"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
type P={id:string;name:string;kills:number;rescues:number;teamKills:number;damage:number};type G={id:string;startedAt:string;winner:"A"|"B"|"";players:P[];pairs:string[][];scores:Record<string,number>};type S={matchName:string;startedAt:string;players:P[];winner:"A"|"B"|"";games:G[]};
const id=()=>Math.random().toString(36).slice(2,9);const tail=(n:number)=>Math.abs(n||0)%10||10;const roster=()=>["阿北","橘子","阿策","小满"].map(n=>({id:id(),name:n,kills:0,rescues:0,teamKills:0,damage:0}));
const empty=():S=>({matchName:"今晚豆子局",startedAt:new Date().toISOString().slice(0,16),players:roster(),winner:"",games:[]});
const normalize=(v:unknown):S=>{const x=v as Partial<S>&{players?:P[]};return x&&Array.isArray(x.players)?{matchName:x.matchName||"豆子局",startedAt:x.startedAt||new Date().toISOString().slice(0,16),players:(x.players||[]).slice(0,4),winner:x.winner||"",games:x.games||[]}:empty()};
function makePairs(ps:P[],seed:string){const sorted=[...ps].sort((a,b)=>tail(a.damage)-tail(b.damage));const same=new Map<number,P[]>();sorted.forEach(p=>same.set(tail(p.damage),[...(same.get(tail(p.damage))||[]),p]));const exact=[...same.values()].find(a=>a.length===2);if(exact){const rest=sorted.filter(p=>!exact.includes(p));return[[exact[0].id,exact[1].id],[rest[0].id,rest[1].id]]}if([...same.values()].some(a=>a.length>=3)){const shuffle=[...sorted].sort((a,b)=>(a.id+seed).localeCompare(b.id+seed));return[[shuffle[0].id,shuffle[1].id],[shuffle[2].id,shuffle[3].id]]}return[[sorted[0].id,sorted[1].id],[sorted[2].id,sorted[3].id]]}
export default function Home(){const[room,setRoom]=useState("BEAN-2026"),[active,setActive]=useState(""),[data,setData]=useState<S>(empty),[status,setStatus]=useState("准备开局"),[platform,setPlatform]=useState("steam");
const load=useCallback(async(v=room)=>{const k=v.trim().toUpperCase();if(!k)return;try{const r=await fetch("/api/rooms/"+encodeURIComponent(k)),j=await r.json();setData(normalize(j.state));setActive(k);setRoom(k);setStatus(j.state?"已同步房间":"新房间已创建")}catch{setStatus("同步暂不可用")}},[room]);
useEffect(()=>{void load("BEAN-2026")},[]);// eslint-disable-line react-hooks/exhaustive-deps
useEffect(()=>{if(!active)return;const t=setTimeout(()=>void fetch("/api/rooms/"+encodeURIComponent(active),{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({state:data})}),500);return()=>clearTimeout(t)},[data,active]);
const pairs=useMemo(()=>data.players.length===4?makePairs(data.players,data.startedAt):[],[data.players,data.startedAt]);const name=(pid:string)=>data.players.find(p=>p.id===pid)?.name||"—";const team=(pid:string)=>pairs.findIndex(a=>a.includes(pid))===0?"A":"B";
const edit=(pid:string,k:keyof P,v:string)=>setData(d=>({...d,players:d.players.map(p=>p.id===pid?{...p,[k]:k==="name"?v:Math.max(0,Number(v)||0)}as P:p)}));
const raw=(p:P)=>p.kills*(data.winner===team(p.id)?2:1)+p.rescues-p.teamKills;const teamTotal=(side:"A"|"B")=>data.players.filter(p=>team(p.id)===side).reduce((n,p)=>n+raw(p),0);const stake=data.winner?teamTotal(data.winner)-teamTotal(data.winner==="A"?"B":"A"):0;const points=(p:P)=>!data.winner?0:team(p.id)===data.winner?stake:-stake;const rank=useMemo(()=>{const out:Record<string,number>={};data.games.forEach(g=>Object.entries(g.scores).forEach(([k,v])=>out[k]=(out[k]||0)+v));data.players.forEach(p=>out[p.name]=(out[p.name]||0)+points(p));return Object.entries(out).sort((a,b)=>b[1]-a[1])},[data.games,data.players,data.winner,pairs,stake]);
const finish=()=>{if(data.players.length!==4)return setStatus("请保持 4 名队员");const scores=Object.fromEntries(data.players.map(p=>[p.name,points(p)]));setData(d=>({...d,games:[...d.games,{id:id(),startedAt:d.startedAt,winner:d.winner,players:d.players,pairs:makePairs(d.players,d.startedAt),scores}],players:d.players.map(p=>({...p,kills:0,rescues:0,teamKills:0,damage:0})),winner:"",startedAt:new Date().toISOString().slice(0,16)}));setStatus("本局已计入总榜，新局已开启")};
const importPubg=async()=>{setStatus("正在拉取最近已结束对局…");try{const r=await fetch("/api/pubg/import",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({platform,players:data.players.map(p=>p.name)})}),j=await r.json();if(!r.ok)throw new Error(j.error);setData(d=>({...d,startedAt:(j.createdAt||new Date().toISOString()).slice(0,16),players:d.players.map(p=>{const x=j.players.find((q:P)=>q.name.toLowerCase()===p.name.toLowerCase());return x?{...p,kills:x.kills,rescues:x.rescues,teamKills:x.teamKills,damage:Math.round(x.damage)}:p})}));setStatus("已导入对局 "+j.matchId.slice(-8))}catch(e){setStatus(e instanceof Error?e.message:"拉取失败")}};
return <main className="min-h-screen bg-[#09111a] text-slate-100"><section className="mx-auto max-w-7xl px-4 py-6 sm:px-8"><header className="mb-6 flex flex-wrap items-center justify-between gap-4 border-b border-slate-700 pb-5"><div><p className="text-xs font-bold tracking-[.24em] text-amber-400">PUBG · FOUR PLAYER LEAGUE</p><h1 className="mt-1 text-3xl font-black">豆子局整场账本</h1></div><div className="flex rounded-xl border border-slate-700 bg-slate-900 p-1"><input aria-label="房间号" value={room} onChange={e=>setRoom(e.target.value)} className="w-32 bg-transparent px-3 text-sm font-bold outline-none"/><button onClick={()=>void load()} className="rounded-lg bg-amber-400 px-4 py-2 text-sm font-black text-slate-950">进入房间</button></div></header>
<div className="grid gap-4 lg:grid-cols-[1.3fr_.7fr]"><section className="rounded-2xl border border-amber-400/25 bg-slate-900 p-5"><div className="flex justify-between"><div><p className="text-xs text-slate-400">当前房间 · {active||room}</p><h2 className="text-xl font-black">{data.matchName} · 第 {data.games.length+1} 局</h2></div><span className="text-sm text-emerald-300">{status}</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm text-slate-300">开场时间<input type="datetime-local" value={data.startedAt} onChange={e=>setData(d=>({...d,startedAt:e.target.value}))} className="mt-1 block w-full rounded-lg border border-slate-600 bg-slate-950 px-3 py-2"/></label><label className="text-sm text-slate-300">PUBG 平台<select value={platform} onChange={e=>setPlatform(e.target.value)} className="mt-1 block w-full rounded-lg border border-slate-600 bg-slate-950 px-3 py-2"><option value="steam">Steam / PC</option><option value="psn">PlayStation</option><option value="xbox">Xbox</option><option value="kakao">Kakao</option></select></label></div><button onClick={()=>void importPubg()} className="mt-3 rounded-lg border border-amber-400/60 px-4 py-2 text-sm font-bold text-amber-300">从 PUBG 导入最近完成对局</button></section>
<section className="rounded-2xl border border-slate-700 bg-slate-900 p-5"><p className="text-xs font-bold tracking-wider text-slate-400">实时总榜</p><ol className="mt-3 space-y-2">{rank.map(([n,v],i)=><li key={n} className="flex justify-between rounded-lg bg-slate-800 px-3 py-2"><span><b className="mr-2 text-amber-300">{i+1}</b>{n}</span><b className="text-emerald-300">{v>0?"+":""}{v} 豆</b></li>)}</ol></section></div>
<section className="mt-5 overflow-hidden rounded-2xl border border-slate-700 bg-slate-900"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-700 px-5 py-4"><div><h2 className="font-bold">本局 · 4 人重新组队</h2><p className="text-xs text-slate-400">伤害尾数相同优先绑定；其余按小尾数组、小尾数组，大尾数组、大尾数组。</p></div><div className="flex gap-2"><button onClick={()=>setData(d=>({...d,players:[...d.players,{id:id(),name:"新队员",kills:0,rescues:0,teamKills:0,damage:0}].slice(0,4)}))} className="rounded-lg border border-slate-600 px-3 py-2 text-sm">补足 4 人</button><button onClick={finish} className="rounded-lg bg-amber-400 px-4 py-2 text-sm font-black text-slate-950">结算本局，开始下一局</button></div></div><div className="grid gap-2 border-b border-slate-800 p-4 sm:grid-cols-2">{pairs.map((pair,i)=><div key={i} className={"rounded-xl px-4 py-3 "+(i?"bg-rose-400/10 text-rose-200":"bg-cyan-400/10 text-cyan-200")}><b>{i?"B 队":"A 队"}</b> · {pair.map(name).join(" + ")}<span className="float-right font-black">{teamTotal(i?"B":"A")} 分</span></div>)}</div><div className="overflow-x-auto"><table className="w-full min-w-[820px] text-left text-sm"><thead className="bg-slate-950/60 text-xs uppercase text-slate-400"><tr><th className="px-5 py-3">队员</th><th>队伍</th><th>击杀</th><th>救人</th><th>杀队友</th><th>伤害</th><th>尾数</th><th>本局豆子</th></tr></thead><tbody>{data.players.map(p=><tr key={p.id} className="border-t border-slate-800"><td className="px-5 py-3"><input value={p.name} onChange={e=>edit(p.id,"name",e.target.value)} className="w-24 bg-transparent font-bold outline-none"/></td><td>{team(p.id)} 队</td>{(["kills","rescues","teamKills","damage"]as const).map(k=><td key={k}><input type="number" min="0" value={p[k]} onChange={e=>edit(p.id,k,e.target.value)} className="w-16 rounded bg-slate-800 px-2 py-1"/></td>)}<td><b className="rounded-full bg-amber-400/15 px-2 py-1 text-amber-300">{tail(p.damage)}</b></td><td><b className={points(p)<0?"text-rose-300":"text-emerald-300"}>{points(p)>0?"+":""}{points(p)}</b></td></tr>)}</tbody></table></div><footer className="flex flex-wrap justify-between gap-3 border-t border-slate-700 px-5 py-4"><span className="text-sm text-slate-400">胜队每人 +{stake}，负队每人 −{stake}；本局合计 = {data.players.reduce((n,p)=>n+points(p),0)}</span><div className="flex gap-2"><button onClick={()=>setData(d=>({...d,winner:d.winner==="A"?"":"A"}))} className={"rounded-lg px-4 py-2 text-sm "+(data.winner==="A"?"bg-cyan-300 text-slate-950":"border border-cyan-400/50 text-cyan-300")}>A 队吃鸡</button><button onClick={()=>setData(d=>({...d,winner:d.winner==="B"?"":"B"}))} className={"rounded-lg px-4 py-2 text-sm "+(data.winner==="B"?"bg-rose-300 text-slate-950":"border border-rose-400/50 text-rose-300")}>B 队吃鸡</button></div></footer></section>
<section className="mt-5 rounded-2xl border border-slate-700 bg-slate-900 p-5"><h2 className="font-bold">历史战绩</h2><div className="mt-3 space-y-2">{data.games.length?data.games.slice().reverse().map((g,i)=><div key={g.id} className="flex flex-wrap justify-between gap-2 rounded-lg bg-slate-800 px-4 py-3 text-sm"><span>第 {data.games.length-i} 局 · {new Date(g.startedAt).toLocaleString("zh-CN")} · {g.winner?g.winner+" 队吃鸡":"未设吃鸡"}</span><span>{Object.entries(g.scores).map(([n,v])=>n+" "+(v>0?"+":"")+v).join(" · ")}</span></div>):<p className="text-sm text-slate-500">还没有完成对局。结算本局后会保留在这里，并计入总榜。</p>}</div></section></section></main>}
